### ISSUE TITLE
Calendar page for md089 7/2019 and 8/2019 crashes on 'desktop' view

### ISSUE THREAD

**Issue by grioux-neo** [cap-md089/capunit-com-v6#17]
**Describe the bug**
Attempting to view calendar for 7/2019 or 8/2019 on md089 in desktop view returns 'Oops something bad..."

**To Reproduce**
1. Go to calendar, use "Prev" or enter 7/2019 in address bar (signed in or not gives same result)
2. adjust browser width to enable 'mobile' mode and reload, and it works

**Expected behavior**
Should load events in desktop mode

**Screenshots**
Not required

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Vivaldi 3.2, Chromium Version 84.0.4147.135 (Official Build) snap (64-bit)

**Smartphone (please complete the following information):**
N/A

**Comment by r-a303931** [comment]
Fixed in commit that hasn't been pushed to production, e9ff6c7a0271eda610ade56ea9722de6c986d46e. Fix will be in upcoming version.
