### ISSUE TITLE
Remove "Publish to Wing calendar" feature

### ISSUE THREAD

**Issue by grioux-neo** [cap-md089/capunit-com-v6#24]
**Is your feature request related to a problem? Please describe.**
Publish to Wing calendar feature is not necessary, creates confusion, and delays new CAPUnit account creation while communicating the requirement and background behind it.

**Describe the solution you'd like**
Comment out current Wing Calendar code.  Can be re-inserted readily if required.

**Describe alternatives you've considered**
Implementing extensive documentation and process.

**Additional context**
N/A

**Comment by r-a303931** [comment]
Resolved in b7f6d84f1a9f203297111d9d2386ee5569434894
